parameters:
  articles:

    article_1:
      id: 1
      image: true
      howOldIs: '-1 days'
      votesUp: 3
      votesDown: 5
      viewsCount: 100
      commentsCount: 8
      isPrimapagina: true
      editorRating: 3

    article_2:
      id: 2
      image: true
      howOldIs: '-10 min'
      votesUp: 0
      votesDown: 5
      viewsCount: 10
      commentsCount: 2
      isPrimapagina: false
      editorRating: 1

    article_3:
      id: 3
      image: true
      howOldIs: ''
      votesUp: 0
      votesDown: 0
      viewsCount: 0
      commentsCount: 0
      isPrimapagina: false
      editorRating: 1

    article_4:
      id: 4
      image: true
      howOldIs: ''
      votesUp: 0
      votesDown: 0
      viewsCount: 0
      commentsCount: 0
      isPrimapagina: true
      editorRating: 1

    article_5:
      id: 5
      image: false
      howOldIs: '-3 hours'
      votesUp: 1
      votesDown: 0
      viewsCount: 10
      commentsCount: 1
      isPrimapagina: false
      editorRating: 1

    article_6:
      id: 6
      image: true
      howOldIs: '-18 hours'
      votesUp: 15
      votesDown: 4
      viewsCount: 35
      commentsCount: 3
      isPrimapagina: true
      editorRating: 1

    article_7:
      id: 7
      image: true
      howOldIs: '-3 days'
      votesUp: 20
      votesDown: 2
      viewsCount: 50
      commentsCount: 5
      isPrimapagina: false
      editorRating: 1

    article_8:
      id: 8
      image: true
      howOldIs: '-1 days'
      votesUp: 1600
      votesDown: 0
      viewsCount: 320
      commentsCount: 40
      isPrimapagina: false
      editorRating: 1

    article_9:
      id: 9
      image: false
      howOldIs: '-1 days'
      votesUp: 0
      votesDown: 5
      viewsCount: 0
      commentsCount: 3
      isPrimapagina: false
      editorRating: 1

    article_10:
      id: 10
      image: true
      howOldIs: '-2 days'
      votesUp: 0
      votesDown: 1000
      viewsCount: 0
      commentsCount: 0
      isPrimapagina: false
      editorRating: 1

    article_11:
      id: 11
      image: true
      howOldIs: '-1 days'
      votesUp: 0
      votesDown: 1000
      viewsCount: 0
      commentsCount: 0
      isPrimapagina: false
      editorRating: 1

    article_12:
      id: 12
      image: true
      howOldIs: '-15 hours'
      votesUp: 2
      votesDown: 1
      viewsCount: 150
      commentsCount: 5
      isPrimapagina: false
      editorRating: 1

    article_13:
      id: 13
      image: true
      howOldIs: '-13 hours'
      votesUp: 2
      votesDown: 6
      viewsCount: 130
      commentsCount: 0
      isPrimapagina: false
      editorRating: 1

    article_14:
      id: 14
      image: true
      howOldIs: '-13 days'
      votesUp: 5
      votesDown: 1
      viewsCount: 30
      commentsCount: 10
      isPrimapagina: false
      editorRating: 1

    article_15:
      id: 15
      image: true
      howOldIs: '-1 months'
      votesUp: 30
      votesDown: 10
      viewsCount: 100
      commentsCount: 30
      isPrimapagina: true
      editorRating: 1

    article_16:
      id: 16
      image: true
      howOldIs: '-1 years'
      votesUp: 30
      votesDown: 10
      viewsCount: 100
      commentsCount: 10
      isPrimapagina: true
      editorRating: 1

    article_17:
      id: 17
      image: true
      howOldIs: '-13 months'
      votesUp: 30
      votesDown: 1
      viewsCount: 140
      commentsCount: 30
      isPrimapagina: true
      editorRating: 1
