services:
    app.service.articles_ranking_builder:
      class: AppBundle\Services\ArticlesRankingBuilder
      arguments:
        - 100
        - 1
        - 10
        - 10
        - 1
        - 10
        - 10

#        - 10
#        - 10
#        - 5
#        - 15
#        - 10
#        - 7
#        - 5

    app.use_case.get_ranked_articles:
      class: AppBundle\UseCase\GetRankedArticles
      arguments:
        - '@app.service.articles_ranking_builder'
        - '%articles%'
