services:
    app.service.articles_ranking_builder:
      class: AppBundle\Services\ArticlesRankingBuilder
      arguments:
        - 4
        - 3
        - 4
        - 5
        - 1
        - 1
        - 1

    app.use_case.get_ranked_articles:
      class: AppBundle\UseCase\GetRankedArticles
      arguments:
        - '@app.service.articles_ranking_builder'
        - '%articles%'
